SPLIT_KEYBOARD = yes
SPLIT_TRANSACTION_ENABLE = yes
OPT_DEFS += -DSPLIT_TRANSACTION_ENABLE

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360
SPLIT_POINTING_ENABLE = yes

SERIAL_DRIVER = vendor

# デバッグ用
CONSOLE_ENABLE = yes
